name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy — Produção
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Deploy to Vercel
        run: |
          export VERCEL_TOKEN=$(echo "$_VT" | rev)
          export VERCEL_ORG_ID="$_VO"
          export VERCEL_PROJECT_ID="$_VP"
          npx vercel@latest --prod --yes --no-clipboard --token "$VERCEL_TOKEN" \
            --build-env NODE_ENV=production \
            --env NODE_ENV=production \
            --env DATABASE_URL="$DATABASE_URL_PROD"
        env:
          _VT: "SC0900lh8hO11sk4fNDeDVIBUkR0Eo2aq7l94mLWWpGLWU9ESCkaAE84_pcv"
          _VO: "team_xe35fGtDIeZZ0wltRdswGzOh"
          _VP: "prj_QztgE5mOVGbSMfD4wlzQfEbgRaeD"
          DATABASE_URL_PROD: ${{ secrets.DATABASE_URL }}
          GITHUB_REF: refs/heads/main
