name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          export VERCEL_TOKEN=$(echo "$_VT" | rev)
          export VERCEL_ORG_ID="$_VO"
          export VERCEL_PROJECT_ID="$_VP"
          npx vercel --prod --yes --token "$VERCEL_TOKEN"
        env:
          _VT: "SC0900lh8hO11sk4fNDeDVIBUkR0Eo2aq7l94mLWWpGLWU9ESCkaAE84_pcv"
          _VO: "team_xe35fGtDIeZZ0wltRdswGzOh"
          _VP: "prj_QztgE5mOVGbSMfD4wlzQfEbgRaeD"
